version: "3"
services:
  server:
    image: node:12.18.4
    working_dir: /code
    ports:
      - 3000:3000
    environment:
      - DB_NAME=tasks
      - DB_CONNECTION=mongodb+srv://siglr:taskspass@mongodb-server.jmrly.mongodb.net/?retryWrites=true&w=majority

    depends_on:
      - db
    volumes:
      - type: bind
        source: ./
        target: /code
    command: bash -c "npm install && npm run dev"

  db:
    image: mongo:latest
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=siglr
      - MONGO_INITDB_DATABASE=tasks
      - MONGO_INITDB_ROOT_PASSWORD=taskspass
volumes:
  dbdata:
